#!/usr/bin/env python



# Importing Modules
import gi
gi.require_version('WebKit', '3.0') 
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, WebKit
import os 

def navrequest(thisview, frame, networkRequest):
    address = networkRequest.get_uri()

view = WebKit.WebView()
view.open("https://github.com/obrevenge/obrevenge-iso/wiki")


sw = Gtk.ScrolledWindow()
sw.add(view)

vbox = Gtk.VBox()
vbox.add(sw)

win = Gtk.Window()
win.set_size_request(1200, 700)
win.connect("destroy", Gtk.main_quit)
win.set_title("OBRevenge Online User Guide")
win.add(vbox)
win.show_all()


Gtk.main()
