pre_install() {
	rm -rf /etc/skel/.config/openbox
}

pre_upgrade() {
	pre_install

}

post_install() {
	rm -rf /etc/skel/.config/openbox
	cp -r /etc/skel/.config/openbox_new /etc/skel/.config/openbox
	rm -rf /etc/skel/.config/openbox_new
	cp -r /etc/skel/.conky_new/* /etc/skel/.conky/
	rm -rf /etc/skel/.conky_new
	rm -rf /usr/share/applications/control_panel/obr-tools
}

post_upgrade() {
	post_install
}
