#!/bin/bash

mkdir ~/.config/autostart

ans=$(zenity  --list  --text "Do you want to add or remove an item from Autostart?" --radiolist  --column "Select" --column "Add/Remove" TRUE Add FALSE Remove)

if [ "$ans" = "Add" ]
		then data=$(yad --window-icon=/usr/share/Icons/obrevenge-redhd2.png --width=500 --title="OBRevenge Autostart" --text="What would you like to start on login?" --form --field="Name" --field="command" --separator=" ")
        name=$(echo $data | awk '{print $1}')
        command=$(echo $data | awk '{print $2}')
        touch ~/.config/autostart/$name.desktop
        echo "[Desktop Entry]" >> ~/.config/autostart/$name.desktop
        echo "Name=$name" >> ~/.config/autostart/$name.desktop
        echo "Exec=$command" >> ~/.config/autostart/$name.desktop
        

		elif [ "$ans" = "Remove"  ]
		then cd ~/.config/autostart
        remove=$(yad --window-icon=/usr/share/Icons/obrevenge-redhd2.png --file-selection --title="Select an application to remove from autostart.")
        rm $remove

		else exit

fi
