#!/bin/bash

# This is a simple script to update the users home directory with new 
# cofiguration files
# Written by Jody James for OBRevenge



# Getting username the person who is logged in
user=$(sudo who | awk '{print $1;}')

# Writing updated files to user's home directory
if [ "$?" = "0" ]
    then su $user -c "rm -rf ~/.config/openbox;cp -r /etc/skel/.config/openbox ~/.config/"
    su $user -c "cp -r /etc/skel/.conky ~/"
fi

